service: xpeppers-academy

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

custom:
  bucketName: academy.xpeppers.com

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    BUCKET_NAME: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join: ['', [Fn::GetAtt: [ XpeppersAcademyBucket, Arn ], '/*'] ]

functions:
  save:
    handler: handler.save
    events:
      - http:
          path: /save
          method: post
          cors: true
  read:
    handler: handler.read
    events:
      - http:
          path: /read
          method: get
          cors: true
  delete:
    handler: handler.delete
    events:
      - http:
          path: /delete
          method: post
          cors: true
resources:
  Resources:
    XpeppersAcademyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"
    XpeppersAcademyBucketPolicy:
      Type: 'AWS::S3::BucketPolicy'
      Properties:
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - "s3:GetObject"
              Resource:
                Fn::Join: ['', [Fn::GetAtt: [ XpeppersAcademyBucket, Arn ], '/*'] ]
        Bucket:
          Ref: XpeppersAcademyBucket