service: xpeppers-academy

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        Fn::Join: ['', [Fn::GetAtt: [ XpeppersAcademyBucket, Arn ], '/*'] ]

functions:
  save:
    handler: handler.save
    events:
      - http:
          path: /save
          method: post
  read:
    handler: handler.read
    events:
      - http:
          path: /read
          method: get

resources:
  Resources:
    XpeppersAcademyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: xpeppers-academy